### ISSUE TITLE
Dead links to images in the Talkdesk Integration Challenge readme

### ISSUE THREAD

**Issue by PedroD** [Talkdesk/challenge#19]
Hello,

I am opening this issue just to notify that some of the images in the [Integration Challenge's readme](https://github.com/Talkdesk/challenge/blob/master/problems/b2_talkdesk_integration.md) are not showing up. Probably their links died.

This is what gets rendered in my browser at the moment:

![Dead image links](http://i.imgur.com/WX1UY5H.png)

**Comment by joninvski** [comment]
ups, @axfcampos do you know where these files now live??

**Comment by axfcampos** [comment]
Not sure what was here before or where they live now. Need to dig into this. But I believe these are not critical information for the challenge.

Again @PedroD sorry for the quality of our docs :( and thanks for pointing stuff out :+1:
