### ISSUE TITLE
Formula doubt

### ISSUE THREAD

**Issue by zeespogeira** [Talkdesk/challenge#25]
Hi, 
the challenge states 
"...external_number_cost should be set to 1c if the call is answered in the web browser, otherwise the price to charge should be the same as Twilio charges for calls to that number."

does this mean, if the optional parameter forawarded_number is filled, then it's charged the same as Twilio?

**Comment by heliodavidcosta** [comment]
Hey @zeespogeira this issue should be open in the specific repository of your challenge. Please make it there and we will answer to you asap
